export const INSERT_CATEGORY="INSERT_CATEGORY";
export const UPDATE_CATEGORY="UPDATE_CATEGORY";
export const DELETE_CATEGORY="DELETE_CATEGORY";
export const GET_CATEGORY_LIST="GET_CATEGORY_LIST";
export const INSERT_USER_DETAILS="INSERT_USER_DETAILS";
export const GET_USER_DETAILS="GET_USER_DETAILS";

export const INSERT_ADDRESS = 'INSERT_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const GET_ADDRESS_LIST = 'GET_ADDRESS_LIST';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
