export const INSERT_CATEGORY="INSERT_CATEGORY";
export const UPDATE_CATEGORY="UPDATE_CATEGORY";
export const DELETE_CATEGORY="DELETE_CATEGORY";
export const GET_CATEGORY_LIST="GET_CATEGORY_LIST";

// User Details Action Types
export const INSERT_USER_DETAILS="INSERT_USER_DETAILS";
export const GET_USER_DETAILS_LIST="GET_USER_DETAILS_LIST";
export const UPDATE_USER_DETAILS="UPDATE_USER_DETAILS";
export const DELETE_USER_DETAILS="DELETE_USER_DETAILS";

export const INSERT_ADDRESS = 'INSERT_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const GET_ADDRESS_LIST = 'GET_ADDRESS_LIST';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
//Product Category Action types
export const INSERT_PRODUCTCATEGORY="INSERT_PRODUCTCATEGORY";
export const UPDATE_PRODUCTCATEGORY="UPDATE_PRODUCTCATEGORY";
export const DELETE_PRODUCTCATEGORY="DELETE_PRODUCTCATEGORY";
export const GET_PRODUCTCATEGORY_LIST="GET_PRODUCTCATEGORY_LIST";
export const GET_PRODUCT_LIST="GET_PRODUCT_LIST";
